services:
  - type: web
    name: nerdtype-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: ~18.0.0
      - key: MONGO_CONN_STRING
        fromDatabase:
          name: nerdtype-db
          property: connectionString
      - key: CLIENT_ORIGIN
        value: https://nerdtype-ui.onrender.com

  - type: web
    name: nerdtype-ui
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: ~18.0.0
      - key: REACT_APP_SOCKET_URL
        value: https://nerdtype-api.onrender.com

databases:
  - name: nerdtype-db
    databaseName: typeracer
    user: admin
